### ISSUE TITLE
Force `ctn-container` to full width

### ISSUE THREAD

**Issue by justinhough** [justinhough/Centurion#22]
@jnorthcott22 requested feature where he noted that his design could not allow for the grid to be used with full page width in certain areas. This feature would be a class addition to allow the `.ctn-container` width to change based on necessity to a design.

`.ctn-full-container {
  width: 100%;
}`

Original use case was part of the fluid grid container, but this case would allow for specific areas to change based on usage not in changing the entire grid max-width for an entire site.

**Comment by justinhough** [comment]
Added feature - no major issues.

**Comment by jnorthcott22** [comment]
Works like a champ - thanks for the quick resolution!
